### ISSUE TITLE
What precisely is a snapshot?

### ISSUE THREAD

**Issue by ckaran** [spacejam/sled#1005]
I know that sled uses snapshots, but I'm not sure what they are, and how they are used.  Are they complete copies of the database at some point in the past?  Can we use them to roll backwards in time?  

I know that there isn't an API for this today, but if snapshots *do* allow us to move back and forth through time, then they would be ideal simulators, deterministic debuggers, etc.

**Comment by spacejam** [comment]
Currently, snapshots are used for recovering the database quickly. They don't store any information other than which pages may live in which locations on-disk. It's just an optimization for opening the database more quickly - although for now it only gets created at startup time, until #978 gets implemented. 

By the way, please feel free to use the discord channel for questions. It's lower overhead for me as a maintainer to answer them there rather than dealing with github issues.

**Comment by ckaran** [comment]
OK, so it sounds like snapshots aren't quite what I thought they were.  I'll treat them as a block box, and ignore them.

I'll try to switch to using discord for the future for questions like this.  Thank you!
