### ISSUE TITLE
Feature request: non-blocking version of watch_prefix

### ISSUE THREAD

**Issue by dignifiedquire** [spacejam/sled#1035]
I was wondering if it would be possible to have a version of `watch_prefix` that is non blocking, to make it easier to poll the incoming events. Maybe sth like 

```rust
pub fn watch_prefix_async<P: AsRef<[u8]>>(&self, prefix: P) -> AsyncSubscriber {}

impl Iterator<Item = Future<Output = Event>> for AsyncSubscriber {}
```

then I could write a non blocking loop like this 
```rust
async fn watch_me() {
  let events = tree.watch_prefix_async(b"cool");

  while let Some(event) = events.next().await {
	match event {
      // .. 
	}
  }
}
```

**Comment by leo-lb** [comment]
It would really be useful for me too!

**Comment by leo-lb** [comment]
https://github.com/spacejam/sled/pull/1037

**Comment by spacejam** [comment]
Thanks for linking, @leo-lb :)

Yeah, an initial sketch for this is happening in #1037!

**Comment by leo-lb** [comment]
@spacejam hey, I'm sorry I havent been able to make use of it yet, or try working on some of it as well, but it will come soon. Currently sorting out other implementation details!

**Comment by spacejam** [comment]
Just merged it into master. There is likely a bit of time before the 0.32 release which will include a bit more reliability work, but here's the way it works in master at the moment:

We now support async subscription to events that happen on key prefixes, because the
`Subscription` struct implements `Future<Output=Option<Event>>`:

```rust
let sled = sled::open("my_db").unwrap();
let mut sub = sled.watch_prefix("");
sled.insert(b"a", b"a").unwrap();
sled.insert(b"a", b"a").unwrap();
drop(sled);
extreme::run(async move {
    while let Some(event) = (&mut sub).await {
        println!("got event {:?}", event);
    }
});
```

If this interface feels horrible, feel free to open another issue. But for now, the single Subscription struct implements both Iterator and Future to work regardless of blocking style.

**Comment by dignifiedquire** [comment]
Thank you very much. Will test it out as soon as I can.
