### ISSUE TITLE
polling watch_prefix panics

### ISSUE THREAD

**Issue by dvc94ch** [spacejam/sled#1050]
sled: latest master 4a6bc86
rustc: 1.42.0 (b8cedc004 2020-03-09)
os: Linux archlinux 5.5.13-arch2-1 #1 SMP PREEMPT x86_64 GNU/Linux

```sh
thread 'async-std/executor' panicked at 'called `Option::unwrap()` on a `None` value', /home/dvc/.cargo/git/checkouts/sled-4d0409c39405d50a/4a6bc86/src/oneshot.rs:70:25
```

**Comment by dvc94ch** [comment]
Finally here's a minimal example:
```rust
fn main() {
    let sled = sled::open("/tmp/my_db").unwrap();
    let mut sub = sled.watch_prefix(b"a");
    sled.remove(b"a").unwrap();
    drop(sled);

    async_std::task::block_on(async move {
        while let Some(event) = (&mut sub).await {
            println!("{:?}", event);
        }
    });
}
```

**Comment by divergentdave** [comment]
The root cause of this is that when a `OneShotFiller` drops, it sets `filled = true` and wakes any threads waiting on its condition variable (as also happens when calling `OneShotFiller::fill`) while leaving `item` as `None`, so `<Oneshot as Future>::poll` will wake up, see `filled` is set, and try to do `state.item.take().unwrap()`. (OneShotFiller is used internally by subscriptions)

This presents a design question, I think that if the filler drops before it's filled, `OneShot` should either return `Pending` forever, or the Future impl should have `type Output = Result<T, _>;` or `type Output = Option<T>;` to allow signaling failure if the filler drops first. (Returning Pending forever could be done by setting `state.fused = true` when the filler drops instead of `state.filled = true`.

**Comment by dvc94ch** [comment]
any progress? would be really cool if this could be fixed soon...

**Comment by spacejam** [comment]
https://github.com/spacejam/sled/pull/1058
