### ISSUE TITLE
Feature Request: IVec::zeroed(capacity)

### ISSUE THREAD

**Issue by jhwgh1968** [spacejam/sled#1122]
#### Use Case:

I am investigating use of sled with values around 190 KiB in size. When the performance of my multi-threaded protoype fell off a cliff, Valgrind told me why: an astonishing number of machine cycles are spent just copying those buffers around.

Digging into it, I was surprised to learn that `Arc<[u8]>` does not have a zero copy cast from `Vec<u8>`, `Box<[u8]>`, or even `Arc<[u8; N]>`!

As a result, I can see no way to avoid copying data at least once into an `IVec` in the current API. I'd like to have a zero-copy way to populate one.

#### Proposed Change:

I propose adding a new method, `IVec::zeroed(capacity)`. It allows an `IVec` to be created in advance of having the data in a buffer somewhere, if the caller knows what the data size will be (my use case), or can tolerate padding (many others, I'm sure).

Example:

```
let db = sled::open_db(...)?.tree(...);
let generator = ... ;
let expected_len = generator.calculate_len();
let dst = IVec::zereoed(expected_len);
let writer = std::io::Cursor::<&mut [u8]>::new(&mut dst);
assert_eq!(generator.write_into(&mut writer), expected_len);

db.insert("my_data".to_bytes(), dst)?;
```

#### Who Benefits From The Change(s)?

Anyone who wants to use large keys and values.

#### Alternative Approaches

I had several other ideas for alternatives, but I imagined they would be more difficult to implement:

1. Make `IVec` have a separate `capacity` like `Vec<T>`, and support incremental pushes to it.
2. Make `IVec` support arbitrary writers to a growing internal buffer, and then shove that into an `Arc<[u8]>` after the writer is finished.
3. Figure out how to write a zero copy cast from an owned `[u8]` type to `sled::Arc<[u8]>`. (I suspect this hasn't been done, because Rust's layout guidelines would make any pointer tricks UB.)

In addition, having an `IVec::filled(capacity, pattern)` method might be more general for protocols and formats who could not tolerate zeroes.

**Comment by divergentdave** [comment]
For what it's worth, converting an `Vec<u8>` or `Box<[u8]>` to an `Arc<[u8]>` without a new allocation and copy is not possible. The allocation that `Arc<[u8]>` makes has a layout with the reference count first, followed by the type `T`, in this case a dynamically sized slice. This is a different layout than both `Box<[u8]>`, which lacks the reference count, and `Vec<u8>`, which lacks the reference count and has a capacity in addition to a length. I believe `Arc<[u8; N]>` is also impossible to convert in the same sense, because the type `T` would be an array with statically known size, which has a different layout than a dynamically sized slice.

A `zeroed` constructor would be tractable, so long as the slice element type can safely be initialized with `std::mem::zeroed()`, like `u8` can.

**Comment by jhwgh1968** [comment]
I have implemented this in a PR, but after getting some feedback, did a more thorough and careful test of the use case that motivated it. In the end, that would not be solved by this.

The need for this has weakened for me. If no one thinks it would be nice to have in general, I am okay with having this issue get closed.
