### ISSUE TITLE
async/await support

### ISSUE THREAD

**Issue by D4nte** [spacejam/sled#1123]
Hi,

I wonder if you considered supporting `async` and `await` Rustlang keywords.

I can see that all provided APIs are blocking, I believe filesystem io is a good usecase for async usage. I am surprised there is no mention of it in the repo, am I missing something obvious?

Cheers.

**Comment by spacejam** [comment]
https://github.com/spacejam/sled#interaction-with-async

**Comment by spacejam** [comment]
My perspective is that async/await is mostly a nice "rust compatibility layer" for folks who are coming to the language from JS and other languages where you're encouraged to use this pattern to avoid callbacks, but when measuring performance of IO, rust's async/await introduces more overhead than it prevents in many situations, and it always adds friction for people writing the system.

I think it's a good fit for load balancers that don't even need to deserialize JSON, but the more CPU usage your operations require, the less benefit async/await can possibly provide.

A lot of people are basing their mindset around threads vs async around C10K, a nice overview of the landscape from 2001, which is now a little out of date due to the reduced costs of context switches and kernels generally improving a lot, making threads a totally viable option for various high concurrency workloads.

The negative performance for sled-like workloads with lots of CPU, combined with the ergonomic issues, means async/await is not appropriate for sled.

**Comment by D4nte** [comment]
I can't believe I missed it in the readme! Thanks for taking the time to write this detailed explanation.
