### ISSUE TITLE
Recommended tree amount per database

### ISSUE THREAD

**Issue by madmaxio** [spacejam/sled#1153]
How many trees is reasonable to store per one database? 
As far as I understand tree is namespace/equivalent of SQL table.

**Comment by spacejam** [comment]
You theoretically could have billions if you're on a 64-bit machine, but every time you create a tree, there is a metadata map which keeps all of the trees in one node in the system, and if you have millions of trees, it may be pretty slow to keep creating and destroying them because sled will write this metadata node in its own file and synchronously fsync it before allowing you to continue. In general, the right approach is to try out an approach and measure what happens according to a realistic workload.

**Comment by madmaxio** [comment]
Thx a lot.
