### ISSUE TITLE
Support Encryption at Rest 

### ISSUE THREAD

**Issue by signupsi** [spacejam/sled#1196]
#### Use Case:
Store encrypted configuration data into sled 
Store encryption keys / certificates
store encrypted data as per business use

**Comment by BlackHoleFox** [comment]
This could be accomplished with a thin structure wrapping over a sled `Db` or `Tree` that holds your key(s) and then all the data that goes through it can be encrypted/decrypted with [a pure Rust AES-GCM](https://crates.io/crates/aes-gcm) implementation when its stored/retrieved. You could even look at using [secrecy](https://crates.io/crates/secrecy) to hold the keys in memory.

**Comment by spacejam** [comment]
I'm hesitant to commit to this in the core of sled because anyone who is likely to require encryption is likely to have specific requirements that may be better met by bypassing the sled implementation and making their own thin wrapper. I'm more likely to support some sort of tree-specific typing feature that can be used for arbitrary serialization, compression, and/or encryption and support all of these in a single abstraction to reduce API surface and internal complexity.

**Comment by naim94a** [comment]
> This could be accomplished with a thin structure wrapping over a sled `Db` or `Tree` that holds your key(s) and then all the data that goes through it can be encrypted/decrypted with [a pure Rust AES-GCM](https://crates.io/crates/aes-gcm) implementation when its stored/retrieved. You could even look at using [secrecy](https://crates.io/crates/secrecy) to hold the keys in memory.

Wouldn't this break sled's API? How would `scan_prefix` work?

**Comment by BlackHoleFox** [comment]
> @naim94a Wouldn't this break Sled's API? ...

That depends if you want to store both your keys and values encrypted or not. You could have all your keys made of non-secret bytes, like UUIDs and timestamps, and scan those, then only decrypting the values relevant. I don't think there's an easy/possible way to re-implement the functionality needed to do on-the-fly decryption for scanning of keys. For many applications though, the first is feasible since leaking what type of data it is (but not the data itself) is acceptable since it really doesn't net an attacker much.
