### ISSUE TITLE
Concurrent log read for single page

### ISSUE THREAD

**Issue by zhongjn** [spacejam/sled#1335]
https://github.com/spacejam/sled/blob/4665afd129480fe3d35ede9708d735cb47113fd8/src/pagecache/mod.rs#L1810-L1815
Currently updates for a page are read in a serial mannar. For scenarios with large worksets and devices not being saturated, page read latency would be significantly reduced if updates were read concurrently.

With `rio` enabled, I guess it could be done by:

1. Make `PageCacheInner::pull` async (allows concurrency within current thread, requires minimum modification), uses `rio` internally.
2. In `PageCacheInner::get`, join all futures from `pull` and perform a blocking wait on the join.

I'm relatively new to the code base, if above approach is appropriate, I could write a PR to address this.

**Comment by spacejam** [comment]
This actually used to be the way things worked, but I measured that the performance difference was not super high, and actually lower on workloads that are highly concurrent already, so I decided to reduce the parallelism here. Reducing threadpool coordination improved efficiency and resulted in a small throughput increase for workloads that were able to otherwise keep desired ssd queue depths at reasonable levels due to concurrent user thread activity on cold working sets.

One reason that this is no longer necessary is that sled has started compacting all pages on page-out, significantly reducing the in-memory and snapshot metadata that needed to be kept for colder pages. When the database crashes and recovers, it's still possible for there to be paged-out pages that have multiple fragments, but this should be a relatively low amount over time. 

The rewrite-on-page-out change was made as part of an ongoing effort to support pointer swizzling, where we will be able to keep all metadata for retrieving paged-out items within an 8-byte pointer (we don't need nearly that many bytes though). This is going to be a really nice improvement for memory usage over time, which is one of the pain points that users have opened a few issues flagging over the last year especially. The rewritten page will probably not be hot in cache since it's being evicted due to inactivity, but it's still in-memory, so pulling it into cache and compressing it to a single contiguous node and writing it to a new location isn't as bad as bouncing it off disk and back as what happens during segment garbage collection.
