### ISSUE TITLE
Feature Request: Encryption

### ISSUE THREAD

**Issue by knpwrs** [spacejam/sled#1342]
#### Use Case:

Encrypting the Database (ala sqlcipher).

#### Proposed Change:

Provide either an interface for built-in encryption or a way to override file io as to enable encryption. 

#### Who Benefits From The Change(s)?

Anyone who wants to encrypt their sled database (same use case as sqlcipher).

#### Alternative Approaches

Encrypt the values that are placed in the database.

**Comment by BlackHoleFox** [comment]
Do the answers on [this issue](https://github.com/spacejam/sled/issues/1196) help at all?

**Comment by spacejam** [comment]
The issue that @BlackHoleFox refers to is still my general view toward this. In addition to the points that were raised in the [linked issue](https://github.com/spacejam/sled/issues/1196), I believe that this would also cause a lot of "safety creep" that will increase the maintenance burden of the project at the very least, resulting in a variety of high-stakes issues over time. While I can make some ill-informed decisions right now about how I might safely choose nonces for AES-GCM-SIV etc... I'm not confident that my ca 2010 undergrad-level understanding of block ciphers is sufficient to address various information leaks and safety margin erosions due to the inherent structure of the database as something with a lot of plaintext that is relatively predictable. A wide variety of questions immediately pop up about the practical security margin degradation of various known plaintext attack opportunities due to the parts of the database that contain fairly low entropy. I don't know how to minimize things like padding overhead for people who want to trade some safety margin for less padding space overhead. Thinking about it for 30 seconds reveals a dozen similar questions whose answers have significant safety implications.

These questions require expert answers that I can't guarantee long-term support for. You can't just slap AES on something with this amount of predictability in the plaintext and call it safely encrypted for any sort of interesting threat model that, presumably, would have led the user to desiring encryption in the first place.

If a user encrypts every key and value before storing it with stock sled, they will leak the number of keys in the database, as well as the approximate key and value lengths, but this information would also be available to anyone who analyzed a database that encrypted every link and replace storage operation in the log (maybe the proportion between key and value sizes would be hidden, but it would be trivial to extrapolate the size of a link with the size of replaces to infer the number of keys in a more fully encrypted database anyway).

**Comment by knpwrs** [comment]
I understand the concern about supporting specific encryption schemes. I think the more interesting approach is some sort of storage adapter that lets the end user transform the bytes on the way to and from the disk. That way I can implement whatever kind of encryption I need and can change it without needing to swap out for new versions of sled.
