### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by theduke** [spacejam/sled#154]
While playing with sled and scanning over the code, I've noticed that a lot of APIs don't return a `Result` but potentially panic instead, which is quite unidiomatic for Rust.

Examples I'm thinking of:

* `Config::default::log/tree()`
* `Log::flush` 
* maybe `Log::write`
* .....

Basically, I guess almost everything that touches disk can fail (flushing, reading, ...).
Dealing with errors is important when using an embedded database, so I'm curious why this is the case. Maybe there is a specific reason?

Also, `Tree::cas` returns a very weird Result type.

**Comment by spacejam** [comment]
Yeah, this is mostly for being as brittle as possible in the initial development stage. I panic all over the place in places where invariants are being violated, which makes bugs often pop out faster. Right now, I'm optimizing for my experience as someone who writes complex code that needs to be safe, at the expense of being too harsh for production usage. Before 1.0 there will be tests added that make sure normal recoverable runtime errors are safely propagated.

`Tree::cas` returns Ok(()) if it succeeded, or the previous value if it did not succeed. The previous value may have been None, or Some(Vec<u8>). What do you think would be a more natural way of modeling these semantics?

**Comment by spacejam** [comment]
FYI I've wrapped all public-facing API's in Result types that propagate things like disk read failures, disk write failures, corrupted data reads, reportable bugs and unsupported usage in https://github.com/spacejam/sled/pull/219

**Comment by theduke** [comment]
@spacejam great.

**Comment by theduke** [comment]
@spacejam you used `()` as an error type almost everywhere, which is just as unidiomatic as panicking. 

Why not provide a proper error type which implementes `Error`?

**Comment by spacejam** [comment]
@theduke feel free to open a PR. building a database is a lot of work, and right now my mind is more on dataloss bugs.

**Comment by theduke** [comment]
@spacejam whoops sorry, I totally missed the `DbResult` part.

**Comment by spacejam** [comment]
More help is very much appreciated :) The directories use `OsStr` internally (although you just need to pass a `AsRef<Path>` from a user perspective) because sometimes we need to mutate them, like adding `.conf`, `.db` or ` .snap.0000000000004BF6` etc... `Path` concatenation results in subdirectories. 

Probably, we should just create a directory for all db files based on the path and store those files with a standard basename. I do think that this approach would result in cleaner code internally. I'll open an issue for that now, and just leave a comment there if it's something you would be interested in helping with.
