### ISSUE TITLE
Advantage of out-of-order IO buffering?

### ISSUE THREAD

**Issue by jeehoonkang** [spacejam/sled#226]
`pagecache/src/io/segment.rs` says:

```rust
//! Another concern that arises due to the fact that
//! IO buffers may be written out-of-order is the
//! correct recovery of segments. If there is data
//! loss in recently written segments, we must be
//! careful to preserve linearizability in the log.
```

But I don't understand what's the advantage of out-of-order IO buffering.  Anyway, the underlying IO syscalls will be sequentialized by the OS, at least in the current implementation (`pagecache/src/io/parallel_io.rs`).  If it's the case, I think it's okay to sequentialize writes to the file in the user-level, avoiding all the problems out-of-order writes incur.  May I ask if I'm missing something here?

**Comment by spacejam** [comment]
Hey! So, maybe I made a mistake, but my reasoning went like this:
* serializing IO means one thread can be calling pwrite(2) at a time for IO buffer writing
* one thread writing at a time might hit a high latency percentile
* all writes after that need to wait for the slow write to complete before being written, head of line blocking
* because we're supporting concurrent access, sometimes a later IO buffer will be sealed and marked as writeable before an earlier one. if we have one thread doing writes, it is waiting on the previous IO buffer to get sealed and marked as writeable before writing the later one
* I want to generally avoid single-thread dependencies, and as the hardware that systems use this with gets more parallel, I want to look a little more like a distributed database to avoid inter-thread dependencies. This has downsides in recovery complexity, though :/ Right now the main exception is the `SegmentAccountant` which is the only thing that can grow a file. We need this to be single-threaded because otherwise we will have file-offset races that can cause concurrent writes to the file from different threads to get partially zeroed out (like when you call truncate on a file to grow it, it fills it with zeroes. when you do a concurrent write that thinks its extending a file, it fills what came before the last known tip with zeroes in a race-prone way).
* it's nice to distribute work across all worker threads, rather than relying on too many threads that only exist to serve one functional purpose, and must be balanced based on workload
* It's nice to perform IO in a smooth way over time, rather than accumulating pending writes while basically sleeping and then write them all out in a burst later.

Does that seem reasonable?

**Comment by spacejam** [comment]
Just realized there's another bug with the implementation, due to the fact that sometimes several IO buffers are written from offsets within the same segment, and if they get written out of order there's room for some non-linearized recovery: https://github.com/spacejam/sled/issues/255

Fun bugs :)

**Comment by spacejam** [comment]
given another year to reflect on this, I'm pretty happy I put in the effort early on to make this out-of-order, as bugs related to it haven't popped up again and it definitely buys us some flexibility with future IO strategies that are being considered
