### ISSUE TITLE
pagecache: `SegmentHeader::prev` seems not used at all

### ISSUE THREAD

**Issue by jeehoonkang** [spacejam/sled#230]
`segment.rs` says:

```
//! 3. This case is solved again by having used
//!    <# io buffers> segments before reuse. We guarantee
//!    that the last <# io buffers> segments will be
//!    present, which means we can write a "previous
//!    log sequence number pointer" to the header of
//!    each segment. During recovery, if these previous
//!    segment Lsn pointers don't match up, we know we
//!    have encountered a lost segment, and we will not
//!    continue the recovery past the detected gap.
```

I assume that `SegmentHeader::prev: LogID` is the "previous log sequence number pointer".  However, it seems it is not used at all, except for de/serialization.  I'd like to ask I understood it correctly.  Thanks!

**Comment by spacejam** [comment]
You did understand it correctly! It is unused, and can be removed. We currently just subtract the fixed segment size from the last <# io buffers> to check that they link up. So, now we just need to rip out the field from the `SegmentHeader` struct, remove the logic dealing with these bytes in the array conversion traits, and subtract 8 from `SEG_HEADER_LEN` to keep everything lined up correctly. If you would like to do this to feel more familiar with it, feel free! Otherwise, I'll probably rip it out in a few days.

**Comment by jeehoonkang** [comment]
@spacejam Thanks for waiting me to resolve this issue!  I tried to do it (https://github.com/jeehoonkang/sled/tree/segment-header-prev), but I failed to make test cases happy with this change.  I couldn't figure out what I did wrong..  In addition, I'm not entire sure how to revise the documentation on the `prev` pointer (https://github.com/jeehoonkang/sled/commit/e67f3de4f486567058bf0f56fcc8f603bd4d0480#diff-002c8a3aef198ede963873c3a81b5676L59)..

**Comment by spacejam** [comment]
@jeehoonkang hmmmm I must have a misplaced assumption somewhere, your code looks correct to me at first glance. These tests catch so many weird issues haha, I'm glad I've been spending most of my time on testing so far :) I'll play around with this for a bit today!

**Comment by spacejam** [comment]
@jeehoonkang I found a bug by running the failing tests with `cargo test crash_recovery -- --nocapture`. This is necessary to show the output of the children of the crash tests, which do forks and kill the process over and over again. The error I got was:

`thread 'test_crash_recovery_no_runtime_snapshot' panicked at 'assertion failed: seg_start + MSG_HEADER_LEN as LogID <= lid', crates/pagecache/src/io/reader.rs:75:8`

I looked at the source, and realized that the assertion was making sure that the reads it was handling were being performed only for data that was located AFTER the segment header, but I must have been pretty tired when I wrote that, because I accidentally wrote `MSG_HEADER_LEN` instead of `SEG_HEADER_LEN`.

I fixed the bug here: https://github.com/spacejam/sled/pull/241 so you should be able to pull in this change and have your tests pass!

My one piece of feedback beyond that is that you can also get rid of the second return argument in `SegmentAccountant::next` which returns the last segment.

Thanks for diving into this! It makes me happy to have more people hacking on the guts of this thing :)
