### ISSUE TITLE
LLAMA-style system transaction?

### ISSUE THREAD

**Issue by jeehoonkang** [spacejam/sled#254]
The [Bw-tree paper](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/bw-tree-icde2013-final.pdf) says that its structure modification operations (SMOs) require the underlying pagestore's system transaction, and the [LLAMA paper](https://www.microsoft.com/en-us/research/publication/llama-a-cachestorage-subsystem-for-modern-hardware/) describes how to implement system transaction.

But maybe it is not necessary at all?  As an evidence, as far as understand, `pagecache` doesn't provide system transaction and `sled` doesn't use system transaction, but they work just fine 😄.  More concretely, it seems the SMO scenarios presented in the Bw-tree paper actually doesn't require atomicity.  Consider the split scenario (Fig. 3), for example.  If the system crashes after flushing (a), then it's just a page leak of `Q`.  That's bad, but these leaks can be detected and removed by other means.  If the system crashes after flushing (b), then it's also possible to detect this anomaly and create an index entry after recovery.  Similarly, it seems system transaction is not necessary in the merge scenario (Fig. 4).

@spacejam, may I ask what do you think of system transactions?  Do you agree my characterization that they are not that necessary, at least for Bw-tree?  Do you have a plan to implement system transaction in `pagecache`?

**Comment by spacejam** [comment]
@jeehoonkang yeah, I agree! (except that `sled` and `pagecache` work just fine, they totally still have bugs!!! hahaha...) This felt like an area of the LLAMA paper that I found a bit unjustified from a Bw-tree perspective, which is why `pagecache` doesn't have any conception of them currently.

Exactly like you said, we [cooperatively complete unfinished SMO's](https://github.com/spacejam/sled/blob/b89660920110db89b81874e100081db1f54fc45e/crates/sled/src/tree/mod.rs#L632) rather than relying on any sort of transactional semantics across updates to multiple pages. I found the papers a bit inconsistent with how they described this, at times I had the impression that they were saying that transactions are required for SMO's, but then describing all of the SMO's in the Bw-tree as fully lock-free and cooperatively completable. 

Maybe you noticed this already, but page merges are also currently unimplemented. This will almost certainly cause a few interesting bugs to pop up due to assumptions around never removing nodes (for example, the `sled::tree::Iter` is incorrect for a `Tree` that merges pages sometimes, because it assumes that the last leaf page it read should be present for the next call to `Iterator::next()`, so this requires a small cleanup to re-read the last key's path and continue from there). I think there might be a few other things with similar assumptions, I need to go back to some old notes.

It might be the case that LLAMA lightweight transactions are in place to simplify building other kinds of structures on top of LLAMA. I can imagine that it makes implementing a tree a lot easier if it supports transactions, and you don't actually care about being fully lock-free. Maybe for the Hekaton hash index? I'm just digging into more of the higher-level transactional literature now for #232 and maybe their reasoning will jump out.

I'm not opposed to adding them, but for now, I  don't have any use cases for that functionality.

**Comment by spacejam** [comment]
Now that https://github.com/spacejam/sled/issues/382 is a major goal, we're actually leaning much harder into transactions in the pagecache than what was described in the LLAMA paper. essentially trying to combine a cicada version chain with a LLAMA delta chain now!
