### ISSUE TITLE
sled_sync crate description

### ISSUE THREAD

**Issue by alexreg** [spacejam/sled#561]
What does "testable" mean in "testable concurrent primitives for the sled database framework"?

**Comment by spacejam** [comment]
hey! I was thinking at one point that I wanted to basically export synchronization primitives, atomic types etc... from the `sled_sync` crate so that when compiling with a test-only feature flag they could be swapped out for versions that call out to schedulers, etc... but I've only put a small amount of stuff around that into that crate so far, mostly just the debug_delay function. it's not really meant for public consumption so I haven't put much energy into the documentation of it

**Comment by alexreg** [comment]
Oh I see. Thsnks for the clarification.
