### ISSUE TITLE
collect statistics on each operation in the benchmark tool

### ISSUE THREAD

**Issue by spacejam** [spacejam/sled#57]
when executing operations, we want to know about:
1. throughput (requests / s)
1. latency (time per request)

For latency, we care about the latency distribution, which means we need to collect percentiles. This is actually a pretty interesting problem, since almost all existing solutions REALLY suck and use probabilistic approches that destroy accuracy. One approach that I like is:
* create a `Vec` of `AtomicUsize` that is pretty big. 
* create a funciton that maps from a measured value to a "slot number"
* each slot number corresponds to values that are ~1% larger than the ones in the previous one
* when measuring something, like latency, convert the latency to the slot number using the function, then look up the `AtomicUsize` and `fetch_add` 1 to it.
* when done with all measurements, you can scan over the counts to determine any percentile. it's good to know, at a minimum, 0th (fastest), 50th (median), 75th, 90th, 95th, 97.5th, 99th, 99.9th, 99.99th, 99.999th, and 100th (max). 

here's an example of a function that converts from a number to a slot number, and back: https://github.com/spacejam/loghisto/blob/master/metrics.go#L316

For throughput, just atomically increment a counter for each of the ops, and have a thread spit out the values every second, resetting it to 0. The latency percentiles can be for the duration of the entire benchmark, for now.

**Comment by pmuens** [comment]
So I just jumped into this one and tried to implement the throughput statistic at first.

I PRed a first WIP implementation with https://github.com/spacejam/rsdb/pull/80. However I'm not sure if the approach is correct. Furthermore I added some `TODO` comments for stuff which needs to be resolved so that it works as expected. However I'm not quite sure yet how those can be resolved.

Would be nice if you could look into it @spacejam and provide some feedback. Will rebase and update the branch accordingly.
