### ISSUE TITLE
CRDT-style page recovery

### ISSUE THREAD

**Issue by spacejam** [spacejam/sled#587]
We can use the log recovery coordinates as a CRDT-style LWW-register for page fragments. This allows us to fully parallelize recovery after crashes, with the only thing that needs to be done serially being the detection of tears in the unstable tip.

**Comment by Kerollmops** [comment]
Ok so, I [read about the CRDT](https://medium.com/@amberovsky/crdt-conflict-free-replicated-data-types-b4bfc8459d26) and searched what does LWW-regsiter means (_last-writer-win_).

Could you please provide some more information of how and where in the code we could work on this? It would be really helpful :)

**Comment by spacejam** [comment]
Part of this will involve parallel snapshot creation, specifically the log recovery iterator should move like this:
* iterate over the dynamic unstable tail on a single thread, in a forward direction
* then iterate over everything else in a reverse direction and in parallel

The reason for reverse iteration when moving beyond the dynamic unstable tail is to reduce the amount of state that is churned out in a shared snapshot. By filling with new information first, we can skip old replaced information immediately without adding it to a shared concurrent map first.

**Comment by spacejam** [comment]
Most of the groundwork for this has been implemented in the Snapshot refactor

**Comment by sitano** [comment]
@spacejam maybe you could drop some lights onto where to look and what to do, or just point out to some other not very hard issues?

**Comment by ckaran** [comment]
Can some version of this be exposed in the public API?  Here's my situation right now:

- I have multiple robots running around, each of which is running sled internally.  Each one maintains a database of what it knows other robots know (basically, every actor replicates every other actor's database).
- Communications is expensive; in some cases the robots are fully disconnected from the network, and will only be able to synchronize when they come back into communications range.  As such, latency can be on the order of hours.  Throughput is pretty bad as well, but not as bad as latency.
- Radio communications are always broadcasts; every robot can listen in on the communications of every other robot that is within range.  There is a mechanism in place for efficiently ACKing and NACKing subsequences of a complete broadcast, so if you're missing 5 KB of a 10 GB broadcast, you can ask for just that portion rather than the whole thing at once.  Think rsync, but as a group.

Under these conditions, it is best to determine the exact point where two robots' databases diverged.  My thought is that the replica would maintain some kind of ID/timestamp/etc. that would act as a unique index value into the original's log.  Once the original receives that information, it knows to package up everything in the log from that point forwards and ship it back to the replica.  Ideally, it would be possible to create any of the [range types](https://doc.rust-lang.org/std/ops/index.html#structs) to describe the parts that are missing.  This would allow a group of replicas to merge their ranges together, so that when the original starts broadcasting the updates it only needs to broadcast it once, allowing the replicas to extract the portions that they need individually and merge them in (sled's [merge](https://docs.rs/sled/0.30.3/sled/struct.Tree.html#method.merge) and [transaction](https://docs.rs/sled/0.30.3/sled/struct.Tree.html#method.transaction) operations are brilliant for this, BTW!).

As a note, if the original doesn't have the identifier in its log, that's fine; it will just ship the contents of the database as a whole out ([export](https://docs.rs/sled/0.30.3/sled/struct.Db.html#method.export) -> [serde](https://crates.io/crates/serde) -> [import](https://docs.rs/sled/0.30.3/sled/struct.Db.html#method.import) for the win).  That means that the log doesn't need to grow indefinitely; once the size of the log exceeds some fraction of the current database's size, there's no point to shipping the log anyways.

**Comment by ckaran** [comment]
I just realized that there is a much less esoteric reason for accessing the log: [git bundle](https://git-scm.com/docs/git-bundle).  That is what I'm thinking about when I think of this issue.

**Comment by spacejam** [comment]
addressed in #978
