### ISSUE TITLE
Writing in sled in not durable

### ISSUE THREAD

**Issue by sticnarf** [spacejam/sled#654]
It is not a bug report.

I know sled has never claimed it has the durability property, but it is also counter-intuitive that a user needs to flush frequently in order to ensure durability when using a **database**.

I hope there will be a note in the doc or readme telling the user: a writing in sled is not durable.

**Comment by spacejam** [comment]
mysql, postgres, redis, basically all databases that aim to compete on any sort of performance metric make the same trade-off. in sled's case we do better than some of them because data is going to be in the OS pagecache, surviving process crashes. for cases where this isn't enough, replication is the way to go about addressing the issue instead of causing terrible queuing issues by blocking everything in a storage engine on fsync.
