### ISSUE TITLE
Is `sled::Db` unwind safe?

### ISSUE THREAD

**Issue by KodrAus** [spacejam/sled#662]
Hi! :wave:

Just wondering whether an instance of `sled::Db` should be unwind safe, and implement the [`UnwindSafe`](https://doc.rust-lang.org/std/panic/trait.UnwindSafe.html) and [`RefUnwindSafe`](https://doc.rust-lang.org/std/panic/trait.RefUnwindSafe.html) traits from std?

I don't have a deep familiarity with the internals of this database yet, but it seems like something worth looking into one way or the other?

**Comment by spacejam** [comment]
Hmm I haven't put much thought into this, but I suspect that it isn't. There are a ton of asserts all over the codebase, generally preferring to crash instead of operating under uncertain conditions, and there are a few areas where I could imagine that a thread that has been assigned responsibility to write an IO buffer could leave the shared state in a condition that would cause future users to lock up. In general, there are a few places where we throw a "ReportableError" back to the user instead of crashing, but my assumption has been that crashing fast is usually the safer bet when durability-impacting unexpected runtime errors occur.

Are you aware of advantages of this other than test friendliness?

**Comment by KodrAus** [comment]
Not being unwind safe is totally reasonable, it's just not something that gets the same attention as other marker traits, so I think there are lots of things that _could_ be unwind safe but aren't, especially if they're already `Send` + `Sync` because they probably already do work to keep their internal state consistent.

I guess the benefit is for upstream consumers that need to try remain online in case of failures, so will want to catch panics. But there are other strategies that consumer could use in that case like poisoning.

**Comment by spacejam** [comment]
Yeah, it's interesting to think about this for the first time. As long as something crashed outside of PageCache io-buffer related code it's safe, or if literally every corner of that codepath was lock free or dealt with poisoned mutexes then it would be unwind safe. But there are a few cold places where linearized execution is enforced with a mutex to make implementation simpler, which don't have a simple way to deal with poisoned mutexes. They could be converted to 100% lock free but I'm feeling like that's a pretty low priority feature though and could make correctness critical but not performance critical paths more risky.
