### ISSUE TITLE
pedantic clippy cleanup

### ISSUE THREAD

**Issue by spacejam** [spacejam/sled#760]
There are many issues when running `cargo clippy -- -W clippy::pedantic` from the root. Most of them are quite easy to fix (please ignore cyclometric complexity issues).

Please help us clean some of them up! Even a single one is helpful!

**Comment by sitano** [comment]
due to the https://github.com/rust-lang/rust-clippy/issues/4091 I think `clippy` must be rather changed to `cargo clippy -- -D clippy::pedantic -A clippy::default_trait_access -A clippy::cast_sign_loss`. 

It does no makes sense to fix those specific warns:
- warning: casting usize to f64 causes a loss of precision on targets with 64-bit wide pointers (usize is 64 bits wide, but f64's mantissa is only 52 bits wide)  --> tests/src/tree.rs:78:41: let gamma = Gamma::new(0.3, gs as f64).unwrap();
- warning: Calling std::cell::RefCell<std::vec::Vec<lock_api::rwlock::RwLockWriteGuard<'_, parking_lot::raw_rwlock::RawRwLock, ()>>>::default() is more clear than this expression
   --> crates/sled/src/tx.rs:334:28 locks: Default::default(), try: `std::cell::RefCell<std::vec::Vec<lock_api::rwlock::RwLockWriteGuard<'_, parking_lot::raw_rwlock::RawRwLock, ()>>>::default()`

**Comment by sitano** [comment]
do you think pedantic naming worth it? (pid <-> lid, lsn <-> len are forbidden)

**Comment by spacejam** [comment]
@sitano Personally I'm fine with these abbreviations because I've seen them every day for the last 3 years, but I think for other people they might not be very descriptive. `pid` would probably be better as `page_id`, `lid` would probably be better as `log_id`, lsn and len though are both kind of idiomatic (LSN in the database world is pretty ubiquitous).

**Comment by sitano** [comment]
@spacejam thats exactly what I did)

**Comment by sitano** [comment]
as far as I saw, there is nothing to fix there anymore. only integer ops related stuff left, naming with module and use of default - all this unfixable.
