### ISSUE TITLE
best way to work around "cannot infer type for `E`" in transaction API

### ISSUE THREAD

**Issue by dusty-phillips** [spacejam/sled#941]
Bug reports must include:
1. sled version: 0.30.3
2. rustc version: 1.40.0
3. operating system: Fedora 31
4. logs: ?

I often want to write code like this, especially in unit tests:
```rust
#[test]
fn test() {
    let db = sled::open(std::path::Path::new("sled")).unwrap();
    let test = db.open_tree("test").unwrap();
    test.transaction(|tree| {
        tree.insert(b"key", b"value")?;
        let value = tree.get(b"key")?.unwrap();
        assert_eq!(value, b"value");
        Ok(())
    })
    .unwrap();
}
```

this fails with: 

```
error[E0282]: type annotations needed
 --> src/lib.rs:none 5:10
  |
5 |         .transaction(|tree| {
  |          ^^^^^^^^^^^ cannot infer type for `E`

error: aborting due to previous error
```

I am actually not sure why this fails because `TransactionResult` has a default error type. And I have similar code in other places that doesn't throw this error, and I can actually figure out the difference.

The best workaround I found is to assign a value to the result and then unwrap it separately:

```rust
#[test]
fn test() {
    let db = sled::open(std::path::Path::new("sled")).unwrap();
    let test = db.open_tree("test").unwrap();
    let result: sled::TransactionResult<(), ()> = test.transaction(|tree| {
        tree.insert(b"key", b"value")?;
        let value = tree.get(b"key")?.unwrap();
        assert_eq!(value, b"value");
        Ok(())
    });
    result.unwrap();
}
``` 

but this lacks elegance, especially in a unit test situation where I might have dozens of lines like this. Can you recommend any patterns that might work better?

**Comment by spacejam** [comment]
Hey @dusty-phillips :) The current transaction API is one I'm definitely not satisfied with, because of issues like this that make it confusing to use. I am a bit frustrated that Rust's type defaults feel a bit less than complete at this point.

One minor compression of the same type information could be to use the turbofish to pass that information along: `test.transaction::<_, (), ()>(|tree| {`

The transaction API is likely to be the piece of existing API surface that will change the most over time. I go back and forth about the various approaches, as there are several possibilities and they all seem to have significant downsides. But maybe once I make a more thorough attempt to plot these pros and cons on a table, maybe some combination will let people fight the API less over time.
