### ISSUE TITLE
Built-in support for easy-to-setup replication

### ISSUE THREAD

**Issue by dumblob** [spacejam/sled#988]
There are already several different issues in the tracker touching on the topic of replication. But none of them general enough IMHO. So I'm adding my 2 cents by pointing out an interesting and easy-to-implement strategy called [CURP](https://blog.acolyer.org/2019/03/15/exploiting-commutativity-for-practical-fast-replication/ ) as one of the candidates for replication mechanisms.

See also https://github.com/antirez/redis/issues/6175 .

**Comment by spacejam** [comment]
Could you expand on what you mean by "general enough"? CURP is less general than more traditional paxos-like protocols under current consideration due to the requirement CURP imposes on having durability units (I mean the things being replicated or stored on disk to represent the operations) be meaningfully commutative in independent ways from each other.

All index nodes effectively don't matter for correctness beyond having a reference to the original left-most leaf node at some point, because all split and merge operations are cooperatively completable across crashes or if a thread gets descheduled before it completes a multi-node operation, but they just serve as an optimization. So, no need to even replicate them from a correctness point of view, but we still will for indexing performance. 

From a correctness point of view, all leaf nodes have potentially cyclical dependency graphs on other leaf nodes, as they originally are split from the left-most leaf node and if the database shrinks they may merge back into it again. A log makes it much easier to replicate this fairly dense dependency graph.

A really nice benefit of replicating and storing all operations in sled in a way that is based around tree nodes, rather than a sequence of operations on key-value pairs, is that we can perform aggressive prefix encoding on all logged delta operations on tree nodes, and often keys turn into a single byte.

**Comment by dumblob** [comment]
Well, if there is "not enough commutativity" in *sled*, then yes, CURP won't be efficient (will degrade to "sync & wait" each time). But I wonder whether any time-windowing in *sled* could be exploited (or introduced) for this purpose?

**Comment by spacejam** [comment]
@dumblob One place it probably is worth the effort is to replicate chunks of data in the same place from write_to_log where chunks of data are written to disk, possibly out of order. I think it would make sense to replicate those out of order as well over a multiplexed stream of some sort, and have it piggy-back on the same stability tracking code that is in use already.

But this is a stretch thing, and right now the main focus for sled is to be a rock-solid embedded database that users have their own bespoke replication for and build atop.
