### ISSUE TITLE
Minor API proposal: change `From` to `Into`

### ISSUE THREAD

**Issue by Lucretiel** [spacejam/sled#999]
Several `Tree` methods (insert being the most obvious) have an interface like this:

```rust
fn modify<V>(&self, value: V)
    where IVec: From<V> { ... }
```

I propose changing these to `where V: Into<IVec>`, for the following reasons:

- It allows a *slightly* larger set of input types, as there are rare cases where `Into<T>` can be implemented but `T: From<U>` cannot.
- It allows the trait bound to be on `V`, the input parameter type, which personally I find to be cleaner than an indirect bound on `IVec`.
- Generally, using `Into<T>` is more common in Rust APIs [citation needed].
- This is a strictly forwards-compatible change, because `T: From<U>` implies `U: Into<T>`.

I'm happy to go through and make this change myself, but I wanted to first propose the change and get feedback / approval.

**Comment by spacejam** [comment]
@Lucretiel yeah that's a good point, I think I just had the blanket recommendation of "use From not Into" into my head without thinking at all, not remembering that recommendation is for implementing the traits themselves rather than interfaces which accept them. 

I'd gladly accept that change as long as it doesn't cause gnarly API breakage in some unforeseen way, which I don't think will happen!

**Comment by Lucretiel** [comment]
Great! Can you assign this bug to me so that I don't lose track of it?

**Comment by spacejam** [comment]
Sure!
